#!/usr/bin/python

import logging
import os
import subprocess
import sys

real_path = os.path.realpath(__file__)
root = os.path.abspath(os.path.join(os.path.dirname(real_path), '..', '..'))
sys.path.insert(0, os.path.abspath(root))

from gitspace import builders


def handle_ref(old_sha, new_sha, ref_name):
  branch_names = []
  proc = subprocess.Popen(
      ['/usr/bin/git', 'rev-parse', '--symbolic', '--abbrev-ref', ref_name],
      stdout=subprocess.PIPE)

  for line in proc.stdout:
    branch_name = line.strip()
    if branch_name:
      branch_names.append(branch_name)

  for branch in branch_names:
    logging.info('Building branch {}...'.format(branch))
    repo_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
    ident = str(repo_dir.split('/')[-1])
    builders.Builder.run(ident, repo_dir, branch=branch)


if __name__ == '__main__':
  for line in sys.stdin:
    handle_ref(*line.split())
